# Generated by Django 5.1.2 on 2024-11-03 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_at', models.DateField(auto_now_add=True)),
                ('Updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('datetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Employ.datetime')),
                ('Name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
            bases=('Employ.datetime',),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('datetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Employ.datetime')),
                ('Name', models.CharField(max_length=200)),
                ('Salary', models.IntegerField()),
                ('Department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employ.department')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
            bases=('Employ.datetime',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('datetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Employ.datetime')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Retired', 'Retired'), ('Leave of Absence', 'Leave of Absence')], max_length=200, null=True)),
                ('Department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employ.department')),
                ('Position_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employ.position')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employes',
            },
            bases=('Employ.datetime',),
        ),
    ]
